### ISSUE TITLE
Bug: Dialogues aren't processed correctly when the verb SAY is omitted

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#73]
When the player omits the verb SAY in a dialogue, the parser assigns the following verb to VERB0.
Example SAY RANGER THROW THE ROPE works fine, while in RANGER THROW THE ROPE, the verb THROW becomes VERB0.

```
 start_at = my_location

locations {
   my_location : location "You are in a room with the ranger." ;
}

on_command {

   : if (noun0_is "ranger" && (verb0_is "say" || verb0_is "")) {
      : match "throw rope" {
         : print "The ranger throws the rope";
         : done ;
      }
      : match "_ _"  {
         : print "Eh? ... says the ranger." ;
         : done ;
      }
   :done;}
}
```

Please notice that this used to work correctly in previous builds.

**Comment by ainslec** [comment]
Fixed in 35f.

**Comment by hnejfnvjojgrogjwm** [comment]
The issue is back, please reopen.
It happens with one specific character. Please find screenshots attached for more details.

This is the correct behaviour with SAY BEN HELLO:
![01 - correct behaviour](https://user-images.githubusercontent.com/65968239/84208169-09df9a80-aaab-11ea-8bb2-3ff74cf46052.jpg)

Incorrect behaviour with BEN HELLO. A mysterious verb (SLARTIBARDFAST) is introduced.
![02 - incorrect behaviour 1](https://user-images.githubusercontent.com/65968239/84208171-0a783100-aaab-11ea-91a8-5e6e00e93c67.jpg)

![02 - incorrect behaviour 2](https://user-images.githubusercontent.com/65968239/84208173-0b10c780-aaab-11ea-81a2-87e3701a419b.jpg)

This is the correct behaviour when I try the same thing with a different NPC: JIM HELLO
![03 - correct behaviour, different NPC](https://user-images.githubusercontent.com/65968239/84208177-0ba95e00-aaab-11ea-88cc-59d5c26dc171.jpg)

**Comment by ainslec** [comment]
Having trouble narrowing down this error.

The following program works for the following inputs

SAY BEN HELLO
BEN HELLO
BEN, HELLO

```
start_at                 = my_location

locations {
   my_location : location "You are in a room." ;
}

on_command {
   : if (verb0_is "say" || verb0_is "") {
      : if (noun0_is "ben" && verb_is "hello") {
         : print "Winner" ;
      }
   }
}
```

I may need to see a fuller example of the source that is breaking so I can isolate the issue.

**Comment by ainslec** [comment]
Fixed this issue (again).

It appears that when a noun (that was also an adjective) started the sentence, that adventuron would assign two words to the pre-sentence (then sentence part that holds the optional command noun and noun0),, rather than one (even if the next word was a verb).

e.g.

BEN HELLO

^ If ben was a noun and an adjective, then the active part (verb1, noun1, etc) of the sentence would start at index 2 (0 based) when really it should start at index 1. In the above example, where HELLO is a verb, a verb that follows a sentence that starts with a noun should be verb1, but thanks to the bug, it was simply factored out.

Anyway - it's fixed ( SentenceTokenizer.java ).
